prefixe([e,n,c,y,c,l,o,p,é,d]).
prefixe([t,h,e,r,i,z,i,n,o]).
prefixe([é,l,é,p,h,a,n,t,o]).
prefixe([s,p,o,n,d,y,l,o]).
prefixe([p,s,i,t,t,a,c,o]).
prefixe([p,a,n,t,h,e,r,a]).
prefixe([s,p,l,a,n,c,h,n]).
prefixe([p,e,l,e,c,a,n,i]).
prefixe([c,r,i,s,t,a,t,u]).
prefixe([p,r,o,b,ο,s,c,i]).
prefixe([p,o,s,é,i,d,o,n]).
prefixe([c,a,r,c,h,a,r,o]).
prefixe([i,r,r,i,t,a,t,o]).
prefixe([s,a,c,c,h,a,r,o]).
prefixe([a,n,t,h,r,o,p,o]).
prefixe([r,h,a,m,p,h,o]).
prefixe([h,i,s,p,a,n,o]).
prefixe([g,o,m,p,h,i,o]).
prefixe([g,i,r,a,f,f,a]).
prefixe([l,a,c,r,y,m,o]).
prefixe([c,a,l,y,p,t,o]).
prefixe([t,y,r,a,n,n,o]).
prefixe([e,n,c,y,c,l,o]).
prefixe([d,e,u,t,e,r,o]).
prefixe([o,r,n,i,t,h,o]).
prefixe([p,a,r,a,d,o,x]).
prefixe([d,r,o,m,a,e,o]).
prefixe([s,t,y,r,a,c,o]).
prefixe([a,n,a,t,o,m,o]).
prefixe([s,t,r,e,p,t,o]).
prefixe([f,r,a,n,c,o]).
prefixe([é,l,e,c,t,r]).
prefixe([d,i,d,a,c,t]).
prefixe([d,i,c,t,i,o]).
prefixe([d,a,c,t,y,l]).
prefixe([a,n,k,y,l,o]).
prefixe([é,r,y,t,h,r]).
prefixe([c,i,r,c,u,m]).
prefixe([c,i,r,c,o,n]).
prefixe([g,l,o,s,s,o]).
prefixe([g,n,a,t,h,o]).
prefixe([g,o,m,p,h,i]).
prefixe([g,o,m,p,h,o]).
prefixe([c,h,o,r,d,a]).
prefixe([g,y,n,é,c,o]).
prefixe([h,é,t,é,r,o]).
prefixe([s,c,h,i,s,t]).
prefixe([c,h,a,s,m,o]).
prefixe([h,y,l,a,e,o]).
prefixe([c,é,p,h,a,l]).
prefixe([r,h,y,n,c,h]).
prefixe([t,h,y,r,e,o]).
prefixe([h,y,m,é,n,o]).
prefixe([i,g,u,a,n,o]).
prefixe([t,i,t,a,n,o]).
prefixe([k,i,n,é,s,i]).
prefixe([c,a,r,c,i,n]).
prefixe([b,r,o,n,t,o]).
prefixe([m,a,l,a,c,o]).
prefixe([r,a,p,t,o,r]).
prefixe([m,o,r,p,h,o]).
prefixe([q,u,i,n,q,u]).
prefixe([n,o,t,h,r,o]).
prefixe([n,y,m,p,h,o]).
prefixe([o,d,o,n,t,o]).
prefixe([b,r,o,n,c,h]).
prefixe([o,u,r,a,n,o]).
prefixe([b,r,a,c,h,i]).
prefixe([v,e,l,o,c,i]).
prefixe([b,a,c,i,l,l]).
prefixe([a,r,t,h,r,o]).
prefixe([a,r,c,h,é,o]).
prefixe([p,h,y,s,i,o]).
prefixe([p,l,e,c,t,o]).
prefixe([p,o,t,a,m,o]).
prefixe([l,a,c,t,o]).
prefixe([s,p,l,é,n]).
prefixe([e,m,b,r,y]).
prefixe([h,y,p,e,r]).
prefixe([r,é,t,r,o]).
prefixe([p,i,s,c,i]).
prefixe([p,h,y,t,o]).
prefixe([s,a,u,r,o]).
prefixe([p,h,o,t,o]).
prefixe([p,h,o,r,a]).
prefixe([a,r,c,h,i]).
prefixe([h,y,d,r,o]).
prefixe([p,e,n,t,a]).
prefixe([p,r,o,n,o]).
prefixe([h,y,a,e,n]).
prefixe([p,a,t,h,o]).
prefixe([p,r,o,t,é]).
prefixe([s,t,é,g,o]).
prefixe([e,i,n,i,o]).
prefixe([p,s,y,c,h]).
prefixe([p,a,l,é,o]).
prefixe([p,a,c,h,y]).
prefixe([c,r,y,p,t]).
prefixe([p,t,e,r,o]).
prefixe([o,r,t,h,o]).
prefixe([b,r,a,d,y]).
prefixe([s,c,h,i,z]).
prefixe([c,a,r,d,i]).
prefixe([b,e,l,g,o]).
prefixe([o,n,y,c,h]).
prefixe([h,é,t,é,r]).
prefixe([d,y,n,a,m]).
prefixe([c,o,n,t,r]).
prefixe([s,c,l,é,r]).
prefixe([t,r,a,n,s]).
prefixe([b,l,a,s,t]).
prefixe([c,o,e,l,o]).
prefixe([d,i,p,l,o]).
prefixe([g,n,a,t,h]).
prefixe([q,u,a,d,r]).
prefixe([s,u,c,h,o]).
prefixe([q,u,a,r,t]).
prefixe([n,i,p,p,o]).
prefixe([g,l,u,c,i]).
prefixe([n,é,c,r,o]).
prefixe([m,y,r,i,a]).
prefixe([g,l,u,c,o]).
prefixe([m,u,l,t,i]).
prefixe([q,u,i,n,t]).
prefixe([s,m,i,l,o]).
prefixe([s,p,a,s,m]).
prefixe([s,u,p,e,r]).
prefixe([c,o,c,c,o]).
prefixe([m,i,l,l,i]).
prefixe([m,i,c,r,o]).
prefixe([g,a,l,l,i]).
prefixe([s,p,e,r,m]).
prefixe([e,x,t,r,a]).
prefixe([t,a,r,b,o]).
prefixe([m,a,s,t,o]).
prefixe([a,l,t,e,r]).
prefixe([a,d,é,n,o]).
prefixe([b,i,b,l,i]).
prefixe([m,a,c,r,o]).
prefixe([b,a,t,h,y]).
prefixe([l,o,p,h,o]).
prefixe([e,t,h,n,o]).
prefixe([l,i,t,h,o]).
prefixe([l,e,p,t,o]).
prefixe([c,h,r,o,n]).
prefixe([s,p,h,é,r]).
prefixe([d,e,i,n,o]).
prefixe([c,h,r,o,m]).
prefixe([l,a,c,r,i]).
prefixe([t,é,t,r,a]).
prefixe([a,n,t,h,o]).
prefixe([a,n,a,t,o]).
prefixe([r,e,c,t,i]).
prefixe([i,n,t,r,a]).
prefixe([i,n,t,e,r]).
prefixe([e,n,t,é,r]).
prefixe([b,u,c,c,o]).
prefixe([u,l,t,r,a]).
prefixe([t,h,é,r,o]).
prefixe([s,p,i,n,o]).
prefixe([s,i,n,o]).
prefixe([p,o,d,o]).
prefixe([e,c,t,o]).
prefixe([c,e,n,t]).
prefixe([s,t,y,l]).
prefixe([p,h,o,n]).
prefixe([p,é,r,i]).
prefixe([c,a,r,n]).
prefixe([p,a,r,a]).
prefixe([t,o,r,o]).
prefixe([p,o,s,t]).
prefixe([p,y,r,o]).
prefixe([v,i,t,a]).
prefixe([o,p,h,i]).
prefixe([a,é,r,o]).
prefixe([o,n,u,x]).
prefixe([o,n,y,x]).
prefixe([o,m,n,i]).
prefixe([p,u,e,r]).
prefixe([o,d,o,n]).
prefixe([o,c,t,e]).
prefixe([o,c,t,a]).
prefixe([o,c,t,o]).
prefixe([a,f,r,o]).
prefixe([n,o,t,o]).
prefixe([x,e,n,o]).
prefixe([m,y,c,o]).
prefixe([m,o,n,o]).
prefixe([m,i,n,u]).
prefixe([m,i,n,i]).
prefixe([a,r,c,h]).
prefixe([m,é,t,a]).
prefixe([m,é,s,o]).
prefixe([m,é,g,a]).
prefixe([m,a,x,i]).
prefixe([m,a,m,m]).
prefixe([a,n,é,m]).
prefixe([l,u,s,o]).
prefixe([l,o,g,o]).
prefixe([x,y,l,o]).
prefixe([d,e,r,m]).
prefixe([a,d,é,n]).
prefixe([a,c,r,o]).
prefixe([r,e,c,t]).
prefixe([k,i,l,o]).
prefixe([d,é,m,o]).
prefixe([a,g,r,i]).
prefixe([a,g,r,o]).
prefixe([d,i,n,o]).
prefixe([d,é,c,i]).
prefixe([d,é,c,a]).
prefixe([h,y,p,o]).
prefixe([a,n,d,r]).
prefixe([h,y,d,r]).
prefixe([h,o,m,o]).
prefixe([a,u,t,o]).
prefixe([h,o,l,o]).
prefixe([a,n,t,o]).
prefixe([h,e,x,a]).
prefixe([c,y,n,o]).
prefixe([h,é,m,o]).
prefixe([h,é,m,i]).
prefixe([c,r,y,o]).
prefixe([s,e,m,i]).
prefixe([s,e,p,t]).
prefixe([t,a,c,h]).
prefixe([a,n,t,a]).
prefixe([g,i,g,a]).
prefixe([c,o,s,m]).
prefixe([a,n,t,é]).
prefixe([e,u,r,o]).
prefixe([a,m,b,i]).
prefixe([é,r,o,t]).
prefixe([c,o,l,i]).
prefixe([t,é,l,é]).
prefixe([a,n,t,i]).
prefixe([t,h,é,o]).
prefixe([e,n,n,é]).
prefixe([c,é,r,o]).
prefixe([c,é,r,a]).
prefixe([s,t,o,m]).
prefixe([p,l,o]).
prefixe([p,r,é]).
prefixe([p,r,o]).
prefixe([p,é,d]).
prefixe([p,a,n]).
prefixe([a,é,r]).
prefixe([o,p,s]).
prefixe([n,é,o]).
prefixe([m,i,m]).
prefixe([m,a,l]).
prefixe([l,é,o]).
prefixe([l,e,o]).
prefixe([i,s,o]).
prefixe([a,n,a]).
prefixe([a,l,t]).
prefixe([r,é,g]).
prefixe([h,y,p]).
prefixe([h,o,m]).
prefixe([h,o,l]).
prefixe([s,c,i]).
prefixe([g,y,n]).
prefixe([s,e,x]).
prefixe([g,é,o]).
prefixe([e,x,o]).
prefixe([e,r,g]).
prefixe([b,a,r]).
prefixe([é,p,h]).
prefixe([a,n,a]).
prefixe([e,n,t]).
prefixe([e,n,d]).
prefixe([é,c,o]).
prefixe([d,y,s]).
prefixe([s,u,b]).
prefixe([d,o,k]).
prefixe([d,o,c]).
prefixe([d,i,s]).
prefixe([d,i,a]).
prefixe([s,y,l]).
prefixe([s,y,n]).
prefixe([c,y,t]).
prefixe([c,o,n]).
prefixe([t,é,l]).
prefixe([t,r,i]).
prefixe([c,a,s]).
prefixe([c,a,d]).
prefixe([c,a,c]).
prefixe([u,n,i]).
prefixe([a,n,o]).
prefixe([b,i,o]).
prefixe([b,é,n]).
prefixe([z,o,o]).
prefixe([é,q,u]).
prefixe([b,i]).
prefixe([c,o]).
prefixe([d,é]).
prefixe([d,i]).
prefixe([u,r]).
prefixe([é,o]).
prefixe([é,p]).
prefixe([e,u]).
prefixe([e,x]).
prefixe([i,n]).
prefixe([i,m]).
prefixe([i,r]).
prefixe([o,b]).
prefixe([o,o]).
prefixe([o,v]).
prefixe([i,l]).
prefixe([r,e]).
prefixe([a,d]).
prefixe([r,é]).
prefixe([a,b]).
prefixe([é]).
prefixe([r]).
prefixe([a]).