suffixe([i,f,i,c,a,t,i,o,n]).
suffixe([i,f,i,c,a,t,e,u,r]).
suffixe([t,r,o,p,h,i,s,m,e]).
suffixe([m,o,r,p,h,i,q,u,e]).
suffixe([s,p,h,é,r,i,q,u,e]).
suffixe([m,o,r,p,h,i,s,m,e]).
suffixe([c,e,n,t,r,i,s,m,e]).
suffixe([d,e,r,m,i,q,u,e]).
suffixe([c,r,a,t,i,q,u,e]).
suffixe([p,h,o,n,i,q,u,e]).
suffixe([f,i,c,a,t,e,u,r]).
suffixe([m,n,é,s,i,q,u,e]).
suffixe([s,c,o,p,i,q,u,e]).
suffixe([m,é,t,r,i,q,u,e]).
suffixe([f,i,c,a,t,i,o,n]).
suffixe([c,é,p,h,a,l,i,e]).
suffixe([l,e,p,t,i,q,u,e]).
suffixe([p,i,t,h,è,q,u,e]).
suffixe([l,o,g,i,q,u,e]).
suffixe([o,d,o,n,t,i,e]).
suffixe([b,o,l,i,q,u,e]).
suffixe([p,l,a,s,t,i,e]).
suffixe([l,o,g,i,s,t,e]).
suffixe([i,s,a,t,i,o,n]).
suffixe([i,l,l,i,a,r,d]).
suffixe([t,e,c,h,n,i,e]).
suffixe([p,h,t,h,o,r,e]).
suffixe([t,h,e,r,m,i,e]).
suffixe([g,r,a,p,h,i,e]).
suffixe([a,c,a,n,t,h,e]).
suffixe([t,r,o,p,h,i,e]).
suffixe([c,u,l,t,e,u,r]).
suffixe([c,u,l,t,u,r,e]).
suffixe([n,o,m,i,q,u,e]).
suffixe([e,c,t,o,m,i,e]).
suffixe([d,a,c,t,y,l,e]).
suffixe([n,o,m,i,s,t,e]).
suffixe([a,b,i,l,i,t,é]).
suffixe([o,u,i,l,l,e,r]).
suffixe([c,é,p,h,a,l,e]).
suffixe([o,u,i,l,l,e]).
suffixe([o,r,e,x,i,e]).
suffixe([o,n,y,m,i,e]).
suffixe([g,n,o,s,i,e]).
suffixe([o,d,o,n,t,e]).
suffixe([p,h,a,g,i,e]).
suffixe([p,h,i,l,i,e]).
suffixe([p,h,o,b,i,e]).
suffixe([p,h,o,n,i,e]).
suffixe([c,r,a,t,i,e]).
suffixe([m,o,r,p,h,e]).
suffixe([m,o,b,i,l,e]).
suffixe([p,h,y,l,l,e]).
suffixe([e,m,m,e,n,t]).
suffixe([m,n,é,s,i,e]).
suffixe([p,l,a,s,m,e]).
suffixe([m,é,t,r,i,e]).
suffixe([m,a,n,c,i,e]).
suffixe([m,a,c,h,i,e]).
suffixe([c,h,r,o,m,e]).
suffixe([r,r,a,g,i,e]).
suffixe([l,o,g,i,e,n]).
suffixe([l,i,n,g,u,e]).
suffixe([s,c,o,p,i,e]).
suffixe([s,p,h,è,r,e]).
suffixe([l,e,p,s,i,e]).
suffixe([l,â,t,r,i,e]).
suffixe([i,s,s,i,m,e]).
suffixe([b,l,a,s,t,e]).
suffixe([i,l,l,i,o,n]).
suffixe([b,i,o,n,t,e]).
suffixe([t,h,è,q,u,e]).
suffixe([t,h,e,r,m,e]).
suffixe([i,a,t,r,i,e]).
suffixe([t,r,o,p,h,e]).
suffixe([g,r,a,p,h,e]).
suffixe([g,r,a,m,m,e]).
suffixe([p,a,t,h,i,e]).
suffixe([g,o,n,i,e]).
suffixe([g,r,a,d,e]).
suffixe([m,a,n,i,e]).
suffixe([g,é,n,i,e]).
suffixe([m,é,l,i,e]).
suffixe([d,o,x,i,e]).
suffixe([h,é,m,i,e]).
suffixe([h,y,d,r,e]).
suffixe([t,y,p,i,e]).
suffixe([i,a,t,r,e]).
suffixe([g,a,m,i,e]).
suffixe([m,è,t,r,e]).
suffixe([o,u,n,e,t]).
suffixe([r,r,h,é,e]).
suffixe([t,r,o,p,e]).
suffixe([s,a,u,r,e]).
suffixe([e,m,e,n,t]).
suffixe([s,c,o,p,e]).
suffixe([p,a,t,h,e]).
suffixe([d,o,x,a,l]).
suffixe([n,a,u,t,e]).
suffixe([i,e,u,s,e]).
suffixe([p,a,u,s,e]).
suffixe([c,e,l,l,e]).
suffixe([i,f,i,e,r]).
suffixe([n,o,m,i,e]).
suffixe([p,é,d,i,e]).
suffixe([i,f,i,e,r]).
suffixe([p,e,x,i,e]).
suffixe([i,l,l,e,r]).
suffixe([p,h,a,g,e]).
suffixe([f,o,r,m,e]).
suffixe([d,e,r,m,e]).
suffixe([o,c,h,e,r]).
suffixe([p,h,a,n,e]).
suffixe([p,h,i,l,e]).
suffixe([c,a,r,p,e]).
suffixe([p,h,o,b,e]).
suffixe([o,ï,q,u,e]).
suffixe([f,l,o,r,e]).
suffixe([c,y,c,l,e]).
suffixe([p,h,o,n,e]).
suffixe([f,i,q,u,e]).
suffixe([i,s,t,a,n]).
suffixe([l,i,t,h,e]).
suffixe([c,r,a,t,e]).
suffixe([p,h,o,r,e]).
suffixe([c,o,s,m,e]).
suffixe([c,o,q,u,e]).
suffixe([p,h,y,t,e]).
suffixe([i,t,i,o,n]).
suffixe([i,t,u,d,e]).
suffixe([o,n,n,e,r]).
suffixe([o,n,y,m,e]).
suffixe([l,a,l,i,e]).
suffixe([l,â,t,r,e]).
suffixe([b,o,c,h,e]).
suffixe([t,i,q,u,e]).
suffixe([o,r,a,m,a]).
suffixe([d,r,o,m,e]).
suffixe([o,r,i,u,m]).
suffixe([c,h,o,r,e]).
suffixe([v,o,q,u,e]).
suffixe([l,o,g,i,e]).
suffixe([t,o,m,i,e]).
suffixe([o,s,i,t,é]).
suffixe([l,o,g,u,e]).
suffixe([s,t,o,m,e]).
suffixe([l,o,g,u,e]).
suffixe([l,o,p,h,e]).
suffixe([s,t,y,l,e]).
suffixe([p,t,è,r,e]).
suffixe([p,t,o,s,e]).
suffixe([e,s,q,u,e]).
suffixe([t,a,p,h,e]).
suffixe([n,o,m,e]).
suffixe([g,è,n,e]).
suffixe([g,y,n,e]).
suffixe([u,r,i,e]).
suffixe([i,q,u,e]).
suffixe([i,b,l,e]).
suffixe([i,c,h,e]).
suffixe([s,o,m,e]).
suffixe([s,t,a,n]).
suffixe([t,y,p,e]).
suffixe([g,o,n,e]).
suffixe([i,è,m,e]).
suffixe([o,n,n,a]).
suffixe([a,b,l,e]).
suffixe([i,e,u,x]).
suffixe([o,q,u,e]).
suffixe([g,a,m,e]).
suffixe([g,a,l,e]).
suffixe([i,l,l,e]).
suffixe([f,u,g,e]).
suffixe([t,e,u,r]).
suffixe([t,u,d,e]).
suffixe([a,c,h,e]).
suffixe([a,c,é,e]).
suffixe([i,o,t,e]).
suffixe([i,q,u,e]).
suffixe([o,t,e,r]).
suffixe([i,s,e,r]).
suffixe([i,s,m,e]).
suffixe([i,s,t,e]).
suffixe([o,t,t,e]).
suffixe([t,i,o,n]).
suffixe([d,o,x,e]).
suffixe([o,u,s,e]).
suffixe([i,t,i,f]).
suffixe([o,u,z,e]).
suffixe([k,i,n,i]).
suffixe([f,i,e,r]).
suffixe([f,i,d,e]).
suffixe([u,c,h,e]).
suffixe([o,y,e,r]).
suffixe([f,è,r,e]).
suffixe([l,i,t,e]).
suffixe([p,a,r,e]).
suffixe([p,è,d,e]).
suffixe([c,y,t,e]).
suffixe([l,y,s,e]).
suffixe([e,s,s,e]).
suffixe([c,u,l,e]).
suffixe([m,a,n,e]).
suffixe([m,e,n,t]).
suffixe([m,è,r,e]).
suffixe([e,r,i,e]).
suffixe([c,o,l,e]).
suffixe([e,n,c,e]).
suffixe([é,m,i,e]).
suffixe([c,i,d,e]).
suffixe([e,l,l,e]).
suffixe([p,o,d,e]).
suffixe([p,o,l,e]).
suffixe([u,l,i,e]).
suffixe([è,d,r,e]).
suffixe([p,o,r,t]).
suffixe([p,y,g,e]).
suffixe([o,c,h,e]).
suffixe([o,d,o,n]).
suffixe([c,è,n,e]).
suffixe([v,o,r,e]).
suffixe([o,ï,d,e]).
suffixe([t,r,o,n]).
suffixe([o,i,r,e]).
suffixe([b,o,l,e]).
suffixe([i,d,e]).
suffixe([i,d,é]).
suffixe([a,c,e]).
suffixe([i,e,l]).
suffixe([i,e,n]).
suffixe([i,e,r]).
suffixe([o,l,e]).
suffixe([o,m,e]).
suffixe([i,n,e]).
suffixe([i,n,g]).
suffixe([i,o,n]).
suffixe([u,l,e]).
suffixe([d,u,n]).
suffixe([b,i,e]).
suffixe([i,t,e]).
suffixe([i,t,é]).
suffixe([i,u,m]).
suffixe([l,i,n]).
suffixe([e,u,x]).
suffixe([e,u,r]).
suffixe([o,s,e]).
suffixe([m,a,n]).
suffixe([t,e,r]).
suffixe([è,m,e]).
suffixe([o,t,e]).
suffixe([-,n,é]).
suffixe([e,a,u]).
suffixe([u,r,e]).
suffixe([a,d,e]).
suffixe([o,i,r]).
suffixe([o,i,s]).
suffixe([i,e]).
suffixe([i,f]).
suffixe([i,n]).
suffixe([i,r]).
suffixe([i,t]).
suffixe([î,t]).
suffixe([e,t]).
suffixe([e,r]).
suffixe([t,é]).
suffixe([u,s]).
suffixe([o,l]).
suffixe([o,n]).
suffixe([o,s]).
suffixe([o,t]).
suffixe([o,u]).
suffixe([u,m]).
suffixe([e,l]).
suffixe([a,c]).
suffixe([u]).
suffixe([s]).
suffixe([o]).
suffixe([i]).
suffixe([é]).
suffixe([e]).
suffixe([a]).
suffixe([x]).